# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Sreenu/OneDrive - IIT Delhi/A/COL215/Assignments/hw3/hw3.srcs/sources_1/ip/filter/filter.xci
# IP: The module: 'filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sreenu/OneDrive - IIT Delhi/A/COL215/Assignments/hw3/hw3.gen/sources_1/ip/filter/filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'filter'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Sreenu/OneDrive - IIT Delhi/A/COL215/Assignments/hw3/hw3.srcs/sources_1/ip/filter/filter.xci
# IP: The module: 'filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Sreenu/OneDrive - IIT Delhi/A/COL215/Assignments/hw3/hw3.gen/sources_1/ip/filter/filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
